package core

import (
	"strings"
	"testing"
)

// 人が打ったもの（ふつう・スラッシュコマンド・!）だけをプロンプトにし、ほかは Note に分ける。
func TestPromptKinds(t *testing.T) {
	b := NewBuilder("claude", "s")
	ts := 1.0
	for _, text := range []string{
		"直して",
		"<command-message>review is running…</command-message>\n<command-name>/review</command-name>\n<command-args>123</command-args>",
		"<bash-input>git status</bash-input>",
		"<local-command-stdout>On branch main</local-command-stdout>",
		"<task-notification><summary>done</summary></task-notification>",
		"Caveat: The messages below were generated by the user while running local commands.",
		"テストも通して\n<system-reminder>Remember the plan.</system-reminder>",
		"[Request interrupted by user]",
	} {
		b.Prompt(&ts, text)
	}
	b.Inject(&ts, "compact", "This session is being continued from a previous conversation.")
	want := []Prompt{{Text: "直して"}, {Text: "/review 123", Kind: KindCommand}, {Text: "! git status", Kind: KindShell}, {Text: "テストも通して"}}
	if len(b.Prompts) != len(want) {
		t.Fatalf("プロンプト %d 件、want %d: %+v", len(b.Prompts), len(want), b.Prompts)
	}
	for i, w := range want {
		if p := b.Prompts[i]; p.Text != w.Text || p.Kind != w.Kind {
			t.Errorf("%d: got %q (%q), want %q (%q)", i, p.Text, p.Kind, w.Text, w.Kind)
		}
	}
	kinds := []string{}
	for _, n := range b.Notes {
		kinds = append(kinds, n.Kind)
	}
	if got, w := strings.Join(kinds, ","), "output,notice,meta,reminder,compact"; got != w {
		t.Errorf("notes %s, want %s", got, w)
	}
	if b.Notes[0].Text != "On branch main" {
		t.Errorf("タグを外していない: %q", b.Notes[0].Text)
	}
	if b.Interrupts != 1 {
		t.Errorf("中断 %d", b.Interrupts)
	}
}
